### ISSUE TITLE
估计loongarch cte.c敲错按键

### ISSUE THREAD

**Issue by czlx-github** [NJU-ProjectN/abstract-machine#14]
![image](https://github.com/NJU-ProjectN/abstract-machine/assets/61815273/db7a4736-9c1d-4e73-8b99-85d1804a07aa)
如上图所示。

**Comment by czlx-github** [comment]
这个问题不严重，劳烦老师修正下就行了。

**Comment by sashimi-yzh** [comment]
已在commit 6f2c34532022bbb0d0c02aac64ff174e9655fc24 中修复
