### ISSUE TITLE
GCC高版本下出错

### ISSUE THREAD

**Issue by WSFcloud** [NJU-ProjectN/abstract-machine#16]
本机环境为wsl下的Debian12，gcc version 12.2.0 。在GCC12上编译选项为ARCH=x86_64-qemu启动会出现问题，ARCH=x86-qemu可以正常启动。
将/abstract-machine/am/src/x86/qemu/boot/Makefile中的gcc改成gcc-11后正常启动。
![Image_1713368053923](https://github.com/NJU-ProjectN/abstract-machine/assets/20496842/c0b59b26-5cbf-4285-aeab-592c00104e68)

/abstract-machine/am/src/x86/qemu/ioe.c在430行左右的__am_lapic_bootap函数中的代码会触发GCC12的"-Warray-bounds" warning

**Comment by phoulx** [comment]
问题不在`ioe.c`，那个"-Warray-bounds"可以直接忽略…
主要是gcc`>=12`版本编译出来的`abstract-machine/am/src/x86/qemu/bootblock.o`无法在64位启动

**Comment by sashimi-yzh** [comment]
那试试这个 https://github.com/NJU-ProjectN/os-workbench-2022/issues/3

**Comment by phoulx** [comment]
`-fno-strict-aliasing`
It works!（可以考虑将该参数加到Makefile中？

**Comment by sashimi-yzh** [comment]
其实这算是代码的问题，应该像上面的issue那样修改源码，而不是添加这个编译选项。

**Comment by sashimi-yzh** [comment]
strict aliasing的问题已在commit [896f1cf](https://github.com/NJU-ProjectN/abstract-machine/commit/896f1cf034a201edf058dc2becc50950c11346d1) 中修复, 可以尝试是否可行

**Comment by JmZeroQAQ** [comment]
老师你有一处地方好像写反了：
````c
    if (u->elf32.e_machine == EM_X86_64) {
*      load_elf64(&u->elf32);
    } else {
*      load_elf32(&u->elf64);
    }
```

**Comment by sashimi-yzh** [comment]
感谢指出，已在commit [de78d6c](https://github.com/NJU-ProjectN/abstract-machine/commit/de78d6ca0a5d399c55f9bae489239f5542d20fe7) 中修复

**Comment by DaHui-BT** [comment]
本机环境为wsl下安装的Ubuntu-22.04，使用的gcc为13.2.0
执行make后出现如下报错
```bash
os-workbench/abstract-machine/am/src/x86/qemu/ioe.c: In function ‘__am_lapic_bootap’:
os-workbench/abstract-machine/am/src/x86/qemu/ioe.c:433:6: error: array subscript 0 is outside array bounds of ‘uint16_t[0]’ {aka ‘short unsigned int[]’} [-Werror=array-bounds=]
  433 |   wrv[0] = 0;
      |   ~~~^~~
cc1: note: source object is likely at address zero
os-workbench/abstract-machine/am/src/x86/qemu/ioe.c:434:6: error: array subscript 0 is outside array bounds of ‘uint16_t[0]’ {aka ‘short unsigned int[]’} [-Werror=array-bounds=]
  434 |   wrv[1] = (uintptr_t)addr >> 4;
      |   ~~~^~~
cc1: note: source object is likely at address zero
```
在添加 --param=min-pagesize=0 参数之后出现如下警告
```bash
x86_64-linux-gnu-ld: warning: trap64.o: missing .note.GNU-stack section implies executable stack
x86_64-linux-gnu-ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
x86_64-linux-gnu-ld: warning: /home/ubuntu/projects/os-lab/os-workbench/test/build/hello-x86_64-qemu.elf has a LOAD segment with RWX permissions
```
之后执行 make run 命令后 qemu处于卡住状态。

**Comment by sashimi-yzh** [comment]
试试参考commit [de78d6c](https://github.com/NJU-ProjectN/abstract-machine/commit/de78d6ca0a5d399c55f9bae489239f5542d20fe7) 修复一下

**Comment by DaHui-BT** [comment]
在参考 commit [de78d6c](https://github.com/NJU-ProjectN/abstract-machine/commit/de78d6ca0a5d399c55f9bae489239f5542d20fe7) 修改main.c之后仍旧存在如下警告信息：
在make时
```bash
x86_64-linux-gnu-ld: warning: os-workbench/test/build/hello-x86_64-qemu.elf has a LOAD segment with RWX permissions
+ CC start.S main.c
/usr/bin/ld: warning: /tmp/cc9yg0vq.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```
在make run时结果能正常显示，没有警告信息，执行正常。

**Comment by sashimi-yzh** [comment]
那就可以了, 上述警告信息可以忽略

**Comment by zhubeilife** [comment]
或者考虑直接加到makefile中？
```diff
+# fix issue https://github.com/NJU-ProjectN/abstract-machine/issues/16
+# 获取gcc版本号
+GCC_VERSION := $(shell $(CC) -dumpversion | cut -f1 -d.)
+# 检查gcc版本是否大于等于1
+ifeq ($(shell [ $(GCC_VERSION) -ge 12 ] && echo true || echo false), true)
+    CFLAGS += --param=min-pagesize=0
+endif
```

**Comment by sashimi-yzh** [comment]
gcc Bugzilla里面说已经在gcc 13.3修复了这个问题, 方便在高版本上试试吗?

**Comment by JmZeroQAQ** [comment]
我在gcc14.1.1版本试了，已经没有这个问题了。

**Comment by sashimi-yzh** [comment]
感谢你的反馈, 后面我再看看怎么修复比较合适.

**Comment by sashimi-yzh** [comment]
已在commit 0e37b474981568f2790f75f5d1105bbb2509515c 中添加`--param=min-pagesize=0`.
