### ISSUE TITLE
Switch condition in cte.c of riscv is misleading

### ISSUE THREAD

**Issue by Cool-Tea** [NJU-ProjectN/abstract-machine#23]
Basic framework in context handling of riscv checks on `mcause` register as branching condition. But this could mislead user to put code of system call in `mcause` register which is against what `mcause` is originally used for. Based on specification of RISC-V, I believe that `mcause` should store the code of exception or interruption specified in the specification, not code of system call. Since the code of system call is stored in `a7`, why not just change the condition to `c->GPR1`? That way, it's less misleading.
```C
Context* __am_irq_handle(Context *c) {
  if (user_handler) {
    Event ev = {0};
    // switch (c->mcause) {  <- This is misleading
    switch (c->GPR1) {
      default: ev.event = EVENT_ERROR; break;
    }

    c = user_handler(ev, c);
    assert(c != NULL);
  }

  return c;
}
```

**Comment by sashimi-yzh** [comment]
You should first check `mcause` before you are sure the exception is caused by `ecall`. It is not misleading. And you should add extra code to distinguish different events.
